PyTorch is an open-source machine learning library developed by Facebook's AI Research lab (FAIR). It is widely used for deep learning and artificial intelligence applications. PyTorch provides a flexible and dynamic computational graph, making it particularly well-suited for research and experimentation.

Key features of PyTorch include:

Dynamic Computational Graph: PyTorch uses a dynamic computational graph, which means that the graph is built on-the-fly as operations are executed. This dynamic nature makes it easier to work with dynamic inputs and changing architectures.

Tensor Computation: PyTorch provides a multi-dimensional array called a tensor, which is similar to NumPy arrays but with additional capabilities. Tensors can be easily manipulated and used for numerical computations, forming the basic building blocks for neural networks.

Autograd: PyTorch includes a built-in automatic differentiation library called Autograd. This allows for the automatic calculation of gradients during the forward pass, which is crucial for training neural networks using techniques like gradient descent.

Neural Network Module: PyTorch provides a torch.nn module for building and training neural networks. This module includes pre-defined layers, loss functions, and optimization algorithms that simplify the process of constructing and training neural network models.

In [2]:
import torch

In [3]:
import numpy as np

In [4]:
torch.__version__

'2.1.2'

In [5]:
arr =np.array([1,2,3,4])

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
arr.dtype

dtype('int64')

In [8]:
type(arr)

numpy.ndarray

In [15]:
# way to convert numpy array t torch tensor
a = torch.from_numpy(arr)

In [16]:
a

tensor([1, 2, 3, 4])

In [17]:
# Another way to create torch_tesnor from numpy array
b = torch.as_tensor(arr)

In [18]:
b

tensor([1, 2, 3, 4])

In [19]:
arr_2d = np.arange(0,12).reshape(4,3)

In [20]:
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
# lets convert it into tensor
tesonr_2d = torch.as_tensor(arr_2d)
tesonr_2d

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

Attention , the two methods which we saw arlier one torch.from_numpy() and another torch.as_tensor(). Both of these methods are actually creates the direct link between array and tesnor. It means that if you change any element inside the array it would have effect over the tensor as well

In [22]:
# if you dont want the direct link 
tensor_array = torch.tensor(arr_2d)

In [23]:
tensor_array

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [24]:
arr_2d[0][2] = 10

In [25]:
arr_2d

array([[ 0,  1, 10],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
tensor_array

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

Creating tensors from scratch
### First of all lets understand the difference between torch.tensor() and torch.Tensor(). 
The only difference is  .tensor() retinas the Int32 dtype. If the data really comsist of integeres only. 
But if we do torch.Tensor() then it is act as an alias to the torch.tensor(). It will convert all dtype to float. 

In [27]:
new_arr = np.array([1,2,3])


In [28]:
tensor = torch.tensor(new_arr)
tensor.dtype

torch.int64

In [29]:
Tensor = torch.Tensor(new_arr)
Tensor.dtype

torch.float32

### Creating empty tensor from scratch


In [30]:
empty_tensor = torch.empty(2,2)

In [31]:
empty_tensor

tensor([[0., 0.],
        [0., 0.]])

In [39]:
# another way to create empty tensor 
zero_tensor = torch.zeros(5,5,dtype = torch.int32)

In [40]:
zero_tensor

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [41]:
ones_tensor  = torch.ones(4,4)

In [42]:
ones_tensor


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [46]:
p = torch.linspace(2,20,5)

In [47]:
p

tensor([ 2.0000,  6.5000, 11.0000, 15.5000, 20.0000])

In [48]:
p.dtype

torch.float32

In [50]:
p = p.type(torch.float64)

In [51]:
p

tensor([ 2.0000,  6.5000, 11.0000, 15.5000, 20.0000], dtype=torch.float64)

In [52]:
# creating random samples
torch.rand(4,3)

tensor([[0.0391, 0.1093, 0.4269],
        [0.1769, 0.3488, 0.8229],
        [0.9286, 0.3180, 0.3653],
        [0.2830, 0.6055, 0.4528]])

In [53]:
# creating the rsandom array but normal distributuon
torch.randn(4,4)

tensor([[ 0.6426,  0.4576,  0.7857, -0.7573],
        [-1.2325,  0.4461, -1.1405,  0.9943],
        [ 1.4045,  0.6080,  0.7167,  0.7903],
        [-1.0814,  0.1498, -0.8804,  2.1761]])

In [54]:
# if we want to genearte array of random integrest
torch.randint(0,10,(5,5))

tensor([[4, 3, 4, 0, 0],
        [0, 4, 3, 3, 0],
        [3, 4, 2, 0, 7],
        [9, 9, 7, 1, 7],
        [8, 2, 3, 2, 5]])

In [64]:
torch.manual_seed(7)
torch.randint(0,10,(1,1))

tensor([[5]])

In [65]:
# making a tensor
a = torch.arange(10)


In [66]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
b = a.view((2,5))
b

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [68]:
c = a.reshape((2,5))
c

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [69]:
a[0] = 10

In [70]:
a

tensor([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [71]:
b

tensor([[10,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [72]:
c

tensor([[10,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

#### reshape and view are actually similar. They does the similar task. Keep in mind that these are directly linked ot the parent array.

#### Another difference is that reshape() can operate on both contiguous and non-contiguous tensor while view() can only operate on contiguous tensor.

## Tensor Operations

In [75]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [86]:
# one way
c = a + b
# second way 
c = torch.add(a,b)
# third way
c = a.add(b)

In [87]:
c

tensor([5., 7., 9.])

In [84]:
# one way
d = torch.mul(a,b)
# second way
d = a.mul(b)
# third way 
d = a * b

In [96]:
# let suppose 
sample_tensor_1 = torch.randn(2,5)
sample_tensor_2 = torch.randn(2,5)

In [99]:
# if you want to reassign smaple_tensor_1 = sample_tensor_1 + sample_tensor_2 then
# using _ we can achieve this reassinging
sample_tensor_1.add_(sample_tensor_2) # same as a = a + b


tensor([[-0.6196, -2.3827,  0.2228,  0.0621, -1.7013],
        [-1.6914, -1.1229,  1.4780, -0.4407, -0.1873]])

In [100]:
# perofrming dot product operation
a = torch.arange(2,10)
b = torch.arange(5,13)


In [104]:
#one way
c = a.dot(b)
# second way
c = torch.dot(a,b)

In [105]:
c

tensor(416)

In [106]:
# profrming matrix multiplication 
p = torch.rand(2,3)
q= torch.rand(3,2)
r = torch.mm(p,q)

In [107]:
r

tensor([[0.2390, 0.8686],
        [0.1665, 0.3149]])

In [108]:
# anothr way 
r = p @ q

In [109]:
r

tensor([[0.2390, 0.8686],
        [0.1665, 0.3149]])

In [115]:
r.shape

torch.Size([2, 2])

In [114]:
r.size()

torch.Size([2, 2])

In [116]:
r.numel()

4

In [125]:
s = torch.randn(10)

In [126]:
s

tensor([ 0.7962, -0.2104, -0.1287, -1.6502,  1.0653,  1.4195,  0.3761, -0.7294,
        -1.4499,  1.4330])

In [127]:
s.norm()

tensor(3.3759)

In [128]:
s.min()

tensor(-1.6502)

In [129]:
s.max()

tensor(1.4330)

In [130]:
s.mean()

tensor(0.0922)

In [131]:
s.std()

tensor(1.1211)