Numpy : It is a numerical processing library which handles the large dataset stored in the form of array.

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]
print(type(mylist))

<class 'list'>


In [4]:
mylist_array = np.array(mylist)
mylist_array

array([1, 2, 3])

In [5]:
#in case of nested list 
mylist = [[1,2,3],[4,5,6]]
mylist_array = np.array(mylist)
mylist_array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#getting the shape of array
mylist_array.shape

(2, 3)

In [10]:
# getting the number of leements
mylist_array.size

6

In [12]:
# make a sample array
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [13]:
# array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# zeros with two dimenstion
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
# you can perform addition operation
p = np.ones((2,2),dtype=int) + 1 # it will add one to every element
p

array([[2, 2],
       [2, 2]])

In [18]:
# you can convert any array to another datatype
q = p.astype(float)
q

array([[2., 2.],
       [2., 2.]])

In [19]:
# if we want to generate array between two numbers such that they are evenly spaced
a = np.linspace(0,100,20)
a

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [21]:
# to generate identity matrix
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
# crreating random number with numpy
np.random.randint(0,100)

95

In [24]:
# if we have to make a random numpy array 
a = np.random.rand(5)
a

array([0.71723689, 0.71985085, 0.23223255, 0.17799481, 0.45087296])

In [25]:
# if we want to make two d random numpy arrya
b = np.random.rand(2,2)
b

array([[0.13638315, 0.49773913],
       [0.38872426, 0.3377646 ]])

In [26]:
# if we want to get standard normal distrivbution. Standard normal distribution has mean of zero.
# and standard deviation of 1
np.random.randn(10)

array([ 0.87840133,  1.41420488,  0.03666293, -0.30123154, -1.31247031,
        1.49050468, -1.81837431, -0.81446388,  0.78665396,  0.19142595])

In [33]:
# random seed is has its effect upto that particular cell only. It don't have impace in another cell
np.random.seed(42)
np.random.randint(2,100)

53

In [35]:
random_arr = np.random.randint(0,100,10)
random_arr

array([99, 23,  2, 21, 52,  1, 87, 29, 37,  1])

In [36]:
# if you want to reshape this array
random_arr.reshape(2,5)

array([[99, 23,  2, 21, 52],
       [ 1, 87, 29, 37,  1]])

In [37]:
# to get the max element in array
random_arr.max()

99

In [38]:
# to get the min element in the arrya
random_arr.min()

1

In [41]:
# to get the index location corresponding the min element and max element 
print(random_arr.argmin())
print(random_arr.argmax())

5
0


In [42]:
# numpy array indexing
arr = np.arange(0,11)


In [43]:
arr[0]

0

In [44]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [45]:
# broadcasting array
a = arr + 100
a

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [46]:
b = arr / 2
b

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [47]:
slice_of_arr = arr[4:6]

In [48]:
slice_of_arr

array([4, 5])

In [52]:
# this is basically pass by reference operation
slice_of_arr[:] = 5

In [53]:
slice_of_arr

array([5, 5])

In [54]:
arr

array([ 0,  1,  2,  3,  5,  5,  6,  7,  8,  9, 10])

In [62]:
# create two d array
arr_2d = np.random.rand(2,2)
arr_2d

array([[0.29214465, 0.36636184],
       [0.45606998, 0.78517596]])

In [63]:
# to take the sum accorss row 
arr_2d.sum(axis = 0)


array([0.74821463, 1.1515378 ])

In [64]:
# to take the sum across columns
arr_2d.sum(axis= 1)

array([0.65850649, 1.24124595])